version: '3'

services:
         nginx:
               image: nginx:latest
               container_name: nginxc
               ports:
                    - 8082:80
               volumes:
                    - web_storage:/var/www/html"
                    - web_conf:/etc/nginx/conf.d/default.conf"
               depends_on:
                    - drupaldb
         drupaldb:
                image: mysql:5.7
                container_name: mysqlserver
                environment:
                         MYSQL_ROOT_PASSWORD: admin@123
                         MYSQL_DATABASE: database1
                         MYSQL_USER: user
                         MYSQL_PASSWORD: user@123
                volumes:
                        - sql_storage:/var/www/html
                restart: always        

         phpmyadmin1:
                image: phpmyadmin/phpmyadmin:latest
                container_name: phpmyadminc
                environment: 
                         MYSQL_ROOT_PASSWORD: admin@123
                         MYSQL_USER: user
                         MYSQL_PASSWORD: user@123
                         PMA_HOST: drupaldb
                         PMA_PORT: 3306
                ports: 
                         - 8081:80
                depends_on:
                         - drupaldb
                restart: always

         drupal1: 
                image: drupal:latest
                container_name: website
                ports: 
                       - 8080:80
                volumes:
                        - web_storage:/var/www/html
                restart: always
                depends_on:
                        - drupaldb
        
volumes:
        sql_storage:
        web_storage:
        web_conf:
                        

                
